apiVersion: "v1"
kind: "Pod"
metadata:
  labels:
    jenkins: "kubectl"
spec:
  containers:
  - args:
    - "cat"
    command:
    - "/bin/sh"
    - "-c"
    image: "lachlanevenson/k8s-kubectl"
    imagePullPolicy: "IfNotPresent"
    name: "kubectl"
    resources:
      limits:
        memory: "512Mi"
        cpu: "500m"
      requests:
        memory: "128Mi"
        cpu: "100m"
    securityContext:
      privileged: false
    tty: true
