apiVersion: "v1"
kind: "Pod"
metadata:
  labels:
    jenkins: "nodejs"
spec:
  containers:
  - args:
    - "cat"
    command:
    - "/bin/sh"
    - "-c"
    image: "lachlanevenson/k8s-kubectl"
    imagePullPolicy: "IfNotPresent"
    name: "kubectl"
    resources:
      limits:
        memory: "4Gi"
        cpu: "500m"
      requests:
        memory: "2Gi"
        cpu: "100m"
    securityContext:
      privileged: false
    tty: true
  - args:
    - "cat"
    command:
    - "/bin/sh"
    - "-c"
    image: "node:10"
    imagePullPolicy: "IfNotPresent"
    name: "nodejs"
    env:
    - name: NODE_OPTIONS
      value: --max_old_space_size=4096
    resources:
      limits:
        memory: "10Gi"
        cpu: "1500m"
      requests:
        memory: "6Gi"
        cpu: "1"
    securityContext:
      privileged: false
    tty: true
  - args:
    - "cat"
    command:
    - "/bin/sh"
    - "-c"
    image: "docker"
    imagePullPolicy: "IfNotPresent"
    name: "docker"
    resources:
      limits:
        memory: "5Gi"
        cpu: "500m"
      requests:
        memory: "3Gi"
        cpu: "100m"
    securityContext:
      privileged: false
    tty: true
    volumeMounts:
    - mountPath: "/var/run/docker.sock"
      name: "volume-0"
      readOnly: false
  hostNetwork: false
  nodeSelector:
    beta.kubernetes.io/os: "linux"
  restartPolicy: "Never"
  securityContext: {}
  volumes:
  - hostPath:
      path: "/var/run/docker.sock"
    name: "volume-0"